- name: Setup project directory
  block: 
  - name: Check If project dir exists
    stat:
      path: "{{ projects.path }}"
    register: project_dir
    changed_when: false

  - name: Create Project directory
    file:
      path: "{{ projects.path }}"
      owner: "{{ current_user }}"
      group: "{{ admin_group }}"
      state: directory
    when: not project_dir.exists
  - name: Create Structure
    shell:
     cmd: "mkdir -p {{ projects.path }}/{{ item }}"
    with_filetree: "{{ projects.path }}"
    loop: "{{ projects.sub_dirs }}"
