---
- name: "Produces the api url for get the latest version of {{ plugin.name }}"
  set_fact:
    latest_plugin_url: "{{ plugins.url.api_last_version | regex_replace('_P_L_U_G_I_N__I_D_', '{{ plugin.id }}') }}"

- name: "Get the file name of {{ plugin.name }} to download"
  shell: "curl -s {{ latest_plugin_url }} | jq -r '.[0].file'"
  register: file_name

- name: "Download and extract {{ plugin.name }}"
  unarchive:
    src: "{{ plugins.url.base }}/{{ file_name.stdout }}"
    dest: "{{ plugin_prefix }}/{{ ide.dest_suffix }}"
    remote_src: yes
