--- 
- name: Set OS distribution dependent variables
  include_vars: "vars/{{ ansible_os_family }}.yml"

- name: "Check if ide config directory exists"
  stat:
    path: "{{plugin_prefix}}/{{ ide.dest_suffix }}"
  register: ide_config
  changed_when: false

- name: "Create ide config directory"
  file:
    path: "{{ plugin_prefix }}/{{ ide.dest_suffix }}"
    state: directory
  when: not ide_config.stat.exists

- name: "Installing plugin into IDE"
  include_tasks: install_plugins.yaml 
  loop: "{{ ide.download }}"
  loop_control:
    loop_var: plugin
