- name: Setup Asdf V}M
  block:
  - name: "Load ASDF"
    shell: 
      cmd: "source /opt/asdf-vm/asdf.sh"

  - name: "Add plugins"
    shell:
      cmd: "asdf plugin add {{ item.name }} {{ item.url }} || [ $? -eq 2 ]"
    loop: "{{ asdf.plugins }}"

  - name: Add gpg to nodejs 
    shell:
      cmd: bash -c '${ASDF_DATA_DIR:=$HOME/.asdf}/plugins/nodejs/bin/import-release-team-keyring'

  - name: Install and set global versions
    shell:
      cmd: |
        asdf install {{ item }}
        asdf list {{ item }} | sort -r | grep -m 1 "" | xargs asdf global {{ item }}
    async: 1000
    poll: 0
    register: asdf_installer
    loop: "{{ asdf.plugins | map(attribute='name') }}"

  - name: Check status of installation version 
    async_status:
      jid: "{{ item.ansible_job_id }}"
      mode: status 
    retries: 100
    delay: 1
    loop: "{{ asdf_installer.results }}"
    register: asdf_installation_checker
    until: asdf_installation_checker.finished
