- name: Setup Asdf V}M
  block:
  - name: "Load ASDF"
    shell: 
      cmd: "source /opt/asdf-vm/asdf.sh"

  - name: "Add plugins"
    shell:
      cmd: "asdf plugin add {{ item.name }} {{ item.url }} || [ $? -eq 2 ]"
    loop: "{{ asdf.plugins }}"

  - name: Add gpg to nodejs 
    shell:
      cmd: bash -c '${ASDF_DATA_DIR:=$HOME/.asdf}/plugins/nodejs/bin/import-release-team-keyring'

  - name: Install and set global versions
    shell:
      cmd: |
        asdf install "{{ item }}"
        asdf list "{{ item }}" | sort -r | grep -m 1 "" | xargs asfd global "{{ item }}"
    loop: "{{ asdf.plugins | map(attribute='name') }}"
