- name: Set OS distribution dependencies variables
  include_vars: "vars/{{ ansible_os_family }}.yaml"
- name: Setup SSH Keys
  block:
  - name: Generate SSH Key
    user:
      name: "{{ current_user }}"
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa
      ssh_key_comment: "{{ user_email }}"
      ssh_key_type: rsa
  - name: Add template files
    become: true
    template:
      src: "{{ item.source }}"
      dest: "{{ item.target }}"
      mode: "{{ item.mode }}"
    loop: "{{ files }}" 
