- name: Setup Dotfiles
  block:
  - name: Download Dotfiles
    git:
      repo: https://github.com/fwfurtado/dotfiles.git
      bare: yes
      dest: "{{ dotfiles.path }}"

  - name: Install Oh-My-Zsh
    shell: 'sh -s "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'

  - name: Install Zinit
    shell: 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma/zinit/master/doc/install.sh)"'

  - name: Update References
    shell:
      chdir: "{{ home_directory }}"
      cmd: "git --git-dir={{ dotfiles.path }} --work-tree={{ home_directory }} checkout"

  - name: Reload and Apply customizations
    shell:
      cmd: "source {{ dotfiles.run_command_file }}"
