- name: Set OS distribution dependencies variables
  include_vars: "var/{{ ansible_os_family }}.yaml"

- name: Setup User
  - name: "Add the user '{{ become_user }}' to the  group '{{ admin_group }}'"
    user:
      name: {{ become_user }}
      shell: {{ shell_path }}
      groups: {{ admin_group }}
      append: yes

  - name: Allow passwordless sudo to group '{{ admin_group }}'
    lineinfile:
      path: /etc/sudoers
      line: '%{{ admin_group }} ALL=(ALL) NOPASSWD: ALL'
    become: true

- name: Install Dependencies
  include: "{{ ansible_os_family }}.yaml"
