- name: Set OS distribution dependencies variables
  include_vars: "vars/{{ ansible_os_family }}.yaml"

- name: Setup User
  block:
  - name: "Add the user current user to admin group"
    become: true
    user:
      name: "{{ user.current }}"
      shell: "{{ user.shell }}"
      groups: "{{ admin_group }}"
      append: yes

  - name: Allow passwordless sudo to group '{{ admin_group }}'
    lineinfile:
      path: /etc/sudoers
      line: '%{{ admin_group }} ALL=(ALL) NOPASSWD: ALL'
    become: true

- name: Install Dependencies
  include_tasks: "{{ ansible_os_family }}.yaml"
