--- 
- name: Setup a new machine
  hosts: localhost
  connection: local
  vars_files: 
    - vars/{{ ansible_os_family }}.yaml
  roles:
    - role: dependencies
    - role: project_dir 
    - role: dotfiles
    - role: asdf
    - role: jet_brains_IDEs_plugins
    - role: ssh_config
